# Linear Regression Multiple Variable

## Problem of predicting home price.

Area|Age|BHK|Price
-|-|-|-
2300|18|3|540000
2600|13|4|588000
3000|10|3|650000
3300|14||679000
3800|5|2|714000
4500|7|4|752000

### Given home prices find out price of a home

In [ ]:
# importing libraries

import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv("house_prices.csv")

In [ ]:
df

area  age  bhk   price
0  2300   18  3.0  540000
1  2600   13  4.0  588000
2  3000   10  3.0  650000
3  3300   14  NaN  679000
4  3800    5  2.0  714000
5  4500    7  4.0  752000

In [ ]:
# data preprocessing: Fill NaN values with median of a column

df.bhk

0    3.0
1    4.0
2    3.0
3    NaN
4    2.0
5    4.0
Name: bhk, dtype: float64

In [ ]:
# get the median values of bhk column

df.bhk.median()

3.0

In [ ]:
# fillna(value)

df.bhk = df.bhk.fillna(df.bhk.median())

In [ ]:
df.bhk

0    3.0
1    4.0
2    3.0
3    3.0
4    2.0
5    4.0
Name: bhk, dtype: float64

In [ ]:
df

area  age  bhk   price
0  2300   18  3.0  540000
1  2600   13  4.0  588000
2  3000   10  3.0  650000
3  3300   14  3.0  679000
4  3800    5  2.0  714000
5  4500    7  4.0  752000

In [ ]:
# creating model

lin_reg = linear_model.LinearRegression()

In [ ]:
new_df = df.drop('price', axis='columns')

In [ ]:
new_df

area  age  bhk
0  2300   18  3.0
1  2600   13  4.0
2  3000   10  3.0
3  3300   14  3.0
4  3800    5  2.0
5  4500    7  4.0

In [ ]:
lin_reg.fit(new_df, df.price)

LinearRegression()

In [ ]:
lin_reg.coef_

array([   87.16167338, -1621.27209445, -9168.19081417])

In [ ]:
lin_reg.intercept_

417694.7041561454

In [ ]:
# get price  of house with 3600 sqft area, 3 bhk, 20 year old


lin_reg.predict([[3600, 3, 20]])

C:\Users\Harsh LogicRays\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([543249.09574831])

In [ ]:
# m1 * area + m2 * bhk + m3 * age + b

# 87.16167338 * 3600 + -1621.27209445 * 3 + -9168.19081417 * 20 + 417694.7041561454

87.16167338 * 3600 - 1621.27209445 * 3 - 9168.19081417 * 20 + 417694.7041561454

543249.0957573954

In [ ]:
bhk = 5
area = 1000
age = 30

In [ ]:
lin_reg.predict([[area, bhk, age]])

C:\Users\Harsh LogicRays\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([221704.29263632])