# KFold Cross Validation


## KFold Cross Validation is a technique to evalute Model Performance.

In [2]:
# importing libraries

from sklearn.linear_model import LogisticRegression

In [3]:
from sklearn.svm import SVC

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
import numpy as np

In [6]:
from sklearn.datasets import load_digits

In [7]:
import matplotlib.pyplot as plt

In [8]:
digits = load_digits()

In [9]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [12]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [14]:
X_train

array([[ 0.,  0.,  4., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16., 12.,  1.],
       [ 0.,  3., 12., ...,  3.,  0.,  0.],
       ...,
       [ 0.,  0.,  7., ...,  9.,  1.,  0.],
       [ 0.,  2., 14., ...,  2.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.]])

In [15]:
y_train

array([7, 6, 5, ..., 8, 3, 7])

In [16]:
# Logistic Regression

log_regr = LogisticRegression(solver="liblinear", multi_class="ovr")

In [17]:
log_regr

LogisticRegression(multi_class='ovr', solver='liblinear')

In [18]:
log_regr.fit(X_train, y_train)

LogisticRegression(multi_class='ovr', solver='liblinear')

In [20]:
log_regr.score(X_test, y_test)

0.9611111111111111

In [21]:
# SVM - support vector machine

svm = SVC(gamma='auto')

In [22]:
svm.fit(X_train, y_train)

SVC(gamma='auto')

In [23]:
svm.score(X_test, y_test)

0.4638888888888889

In [24]:
# Random Forest

random_forest = RandomForestClassifier(n_estimators=30)

In [26]:
random_forest.fit(X_train, y_train)

RandomForestClassifier(n_estimators=30)

In [27]:
random_forest.score(X_test, y_test)

0.9805555555555555

In [28]:
# KFold Cross Validation

from sklearn.model_selection import KFold

In [29]:
kfold_cv = KFold(n_splits=3)

In [30]:
kfold_cv

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
random_data = [i for i in range(100, 201)]

In [32]:
random_data

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200]

In [33]:
kfold_cv.split(random_data)

<generator object _BaseKFold.split at 0x000001E55FE0A0E0>

In [34]:
print(*kfold_cv.split(random_data))

(array([ 34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
        47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])) (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100]), array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52

In [35]:
for train_data, test_data in kfold_cv.split(random_data):
    print(train_data, test_data)

[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51
  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69
  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 100] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  68  69
  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 100] [34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67] [ 68  69  70  71  72  73  74  75  76

In [36]:
random_data = [i for i in range(1, 10)]

In [37]:
random_data

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
print(*kfold_cv.split(random_data))

(array([3, 4, 5, 6, 7, 8]), array([0, 1, 2])) (array([0, 1, 2, 6, 7, 8]), array([3, 4, 5])) (array([0, 1, 2, 3, 4, 5]), array([6, 7, 8]))


In [39]:
for train_data, test_data in kfold_cv.split(random_data):
    print(train_data, test_data)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [40]:
def get_score(mymodel, X_train, X_test, y_train, y_test):
    mymodel.fit(X_train, y_train)
    return mymodel.score(X_test, y_test)

In [42]:
get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test)

0.4638888888888889

In [44]:
get_score(RandomForestClassifier(n_estimators=30), X_train, X_test, y_train, y_test)

0.9638888888888889

In [45]:
svm_score = list()
random_forest_score = list()
log_reg_score = list()

In [46]:
from sklearn.model_selection import StratifiedKFold

In [48]:
kfold_cv = StratifiedKFold(n_splits=3)

In [49]:
for train_data, test_data in kfold_cv.split(digits.data, digits.target):
    print(train_data, test_data)

[ 588  590  591 ... 1794 1795 1796] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 23

In [55]:
for train_index, test_index in kfold_cv.split(digits.data, digits.target):
    X_train = digits.data[train_index]
    X_test =  digits.data[test_index]
    y_train = digits.target[train_index]
    y_test = digits.target[test_index]
    
    svm_score.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    log_reg_score.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    random_forest_score.append(get_score(RandomForestClassifier(n_estimators=30), X_train, X_test, y_train, y_test))

In [56]:
svm_score

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [57]:
log_reg_score

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [58]:
random_forest_score

[0.9282136894824707, 0.9465776293823038, 0.9232053422370617]

In [59]:
# imporing cross_val_score

from sklearn.model_selection import cross_val_score

In [61]:
# svm

cross_val_score(SVC(gamma='auto'), digits.data,  digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [62]:
# logisticRegression

cross_val_score(LogisticRegression(solver="liblinear", multi_class='ovr'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [63]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=3)

array([0.93656093, 0.94323873, 0.92320534])

In [64]:
# parameter tuning

cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=3)

array([0.89649416, 0.9115192 , 0.88981636])

In [65]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target, cv=3)

array([0.90651085, 0.9148581 , 0.9048414 ])

In [66]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=3)

array([0.91652755, 0.94657763, 0.92153589])

In [67]:
cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=5)

array([0.88888889, 0.84722222, 0.92479109, 0.93036212, 0.90250696])

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=10)

array([0.92777778, 0.95      , 0.92777778, 0.83888889, 0.93888889,
       0.91111111, 0.93888889, 0.96648045, 0.8603352 , 0.91061453])

In [69]:
score_one = cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=5)

In [71]:
# average

np.average(score_one)

0.9043144537294955

In [72]:
score_two = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=3)

In [73]:
np.average(score_two)

0.9348914858096827

In [74]:
score_two

array([0.93155259, 0.94657763, 0.92654424])